### ISSUE TITLE
make command issue

### ISSUE THREAD

**Issue by RachelDanie** [rdpstaff/RDPTools#34]
Hello! I see that a number of users have had issues with the make step, but since there have been edits more recently than those threads I wanted to ask about the errors I am getting:ant -f Clustering/build.xml jar
Buildfile: /RDPTools/Clustering/build.xml

download-ivy:
      [get] Getting: http://insecure.repo1.maven.org/maven2/org/apache/ivy/ivy/2.1.0-rc2/ivy-2.1.0-rc2.jar
      [get] To: /root/.ant/lib/ivy.jar
      [get] Not modified - so not downloaded

init-ivy:

resolve:
[ivy:retrieve] :: Ivy 2.1.0-rc2 - 20090704004254 :: http://ant.apache.org/ivy/ ::
[ivy:retrieve] :: loading settings :: file = /RDPTools/Clustering/ivysettings.xml
[ivy:retrieve] :: resolving dependencies :: edu.cme.rdp#clustering;working@metro-pes3307
[ivy:retrieve] 	confs: [default]
[ivy:retrieve] 	found com.sun.xml.bind#jaxb-impl;2.2.7 in maven
[ivy:retrieve] 	found com.sun.xml.bind#jaxb-core;2.2.7 in maven
[ivy:retrieve] 	found javax.xml.bind#jaxb-api;2.2.7 in maven
[ivy:retrieve] 	found com.sun.istack#istack-commons-runtime;2.16 in maven
[ivy:retrieve] 	found com.sun.xml.fastinfoset#FastInfoset;1.2.12 in maven
[ivy:retrieve] 	found javax.xml.bind#jsr173_api;1.0 in maven
[ivy:retrieve] 	found commons-cli#commons-cli;1.2 in maven
[ivy:retrieve] 	found junit#junit;4.8.2 in maven
[ivy:retrieve] 	found commons-codec#commons-codec;1.8 in maven
[ivy:retrieve] 	found commons-io#commons-io;2.4 in maven
[ivy:retrieve] :: resolution report :: resolve 150ms :: artifacts dl 7ms
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   10  |   0   |   0   |   0   ||   10  |   0   |
	---------------------------------------------------------------------
[ivy:retrieve] :: retrieving :: edu.cme.rdp#clustering
[ivy:retrieve] 	confs: [default]
[ivy:retrieve] 	0 artifacts copied, 10 already retrieved (0kB/5ms)

-pre-init:

-init-private:

-init-user:

-init-project:

-init-macrodef-property:

-do-init:

-post-init:

-init-check:

-init-ap-cmdline-properties:

-init-macrodef-javac-with-processors:

-init-macrodef-javac-without-processors:

-init-macrodef-javac:

-init-macrodef-test-impl:

-init-macrodef-junit-init:

-init-macrodef-junit-single:

-init-test-properties:

-init-macrodef-junit-batch:

-init-macrodef-junit:

-init-macrodef-junit-impl:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/3:test-impl

-init-macrodef-testng:

-init-macrodef-testng-impl:

-init-macrodef-test:

-init-macrodef-junit-debug:

-init-macrodef-junit-debug-batch:

-init-macrodef-junit-debug-impl:

-init-macrodef-test-debug-junit:

-init-macrodef-testng-debug:

-init-macrodef-testng-debug-impl:

-init-macrodef-test-debug-testng:

-init-macrodef-test-debug:

-init-debug-args:

-init-macrodef-nbjpda:

-init-macrodef-debug:

-init-macrodef-java:

-init-presetdef-jar:

-init-ap-cmdline-supported:

-init-ap-cmdline:

init:

-deps-jar-init:
   [delete] Deleting: /RDPTools/Clustering/build/built-jar.properties

deps-jar:

-warn-already-built-jar:
[propertyfile] Updating property file: /RDPTools/Clustering/build/built-jar.properties

-check-call-dep:

-maybe-call-dep:

download-ivy:
      [get] Getting: http://insecure.repo1.maven.org/maven2/org/apache/ivy/ivy/2.1.0-rc2/ivy-2.1.0-rc2.jar
      [get] To: /root/.ant/lib/ivy.jar
      [get] Not modified - so not downloaded

init-ivy:

resolve:
[ivy:retrieve] :: loading settings :: file = /RDPTools/AlignmentTools/ivysettings.xml
[ivy:retrieve] :: resolving dependencies :: edu.cme.rdp#AlignmentTools;working@metro-pes3307
[ivy:retrieve] 	confs: [default]
[ivy:retrieve] 	found commons-lang#commons-lang;2.6 in maven
[ivy:retrieve] 	found commons-cli#commons-cli;1.2 in maven
[ivy:retrieve] :: resolution report :: resolve 21ms :: artifacts dl 1ms
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   2   |   0   |   0   |   0   ||   2   |   0   |
	---------------------------------------------------------------------
[ivy:retrieve] :: retrieving :: edu.cme.rdp#AlignmentTools
[ivy:retrieve] 	confs: [default]
[ivy:retrieve] 	0 artifacts copied, 2 already retrieved (0kB/2ms)

-pre-init:

-init-private:

-init-user:

-init-project:

-init-macrodef-property:

-do-init:

-post-init:

-init-check:

-init-ap-cmdline-properties:

-init-macrodef-javac-with-processors:

-init-macrodef-javac-without-processors:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/3:javac

-init-macrodef-javac:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/3:depend

-init-macrodef-test-impl:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/3:test-impl

-init-macrodef-junit-init:

-init-macrodef-junit-single:

-init-test-properties:

-init-macrodef-junit-batch:

-init-macrodef-junit:

-init-macrodef-junit-impl:

-init-macrodef-testng:

-init-macrodef-testng-impl:

-init-macrodef-test:

-init-macrodef-junit-debug:

-init-macrodef-junit-debug-batch:

-init-macrodef-junit-debug-impl:

-init-macrodef-test-debug-junit:

-init-macrodef-testng-debug:

-init-macrodef-testng-debug-impl:

-init-macrodef-test-debug-testng:

-init-macrodef-test-debug:

-init-debug-args:

-init-macrodef-nbjpda:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/1:nbjpdastart

-init-macrodef-debug:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/3:debug

-init-macrodef-java:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/1:java

-init-presetdef-jar:

-init-ap-cmdline-supported:

-init-ap-cmdline:

init:

-deps-jar-init:

deps-jar:

-warn-already-built-jar:
[propertyfile] Updating property file: /RDPTools/Clustering/build/built-jar.properties

-check-call-dep:

-maybe-call-dep:

download-ivy:
      [get] Getting: http://insecure.repo1.maven.org/maven2/org/apache/ivy/ivy/2.1.0-rc2/ivy-2.1.0-rc2.jar
      [get] To: /root/.ant/lib/ivy.jar
      [get] Not modified - so not downloaded

init-ivy:

resolve:
[ivy:retrieve] :: loading settings :: file = /RDPTools/ReadSeq/ivysettings.xml
[ivy:retrieve] :: resolving dependencies :: edu.cme.rdp#ReadSeq;working@metro-pes3307
[ivy:retrieve] 	confs: [default]
[ivy:retrieve] 	found commons-lang#commons-lang;2.6 in maven
[ivy:retrieve] 	found commons-cli#commons-cli;1.2 in maven
[ivy:retrieve] 	found commons-io#commons-io;2.4 in maven
[ivy:retrieve] :: resolution report :: resolve 26ms :: artifacts dl 2ms
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   3   |   0   |   0   |   0   ||   3   |   0   |
	---------------------------------------------------------------------
[ivy:retrieve] :: retrieving :: edu.cme.rdp#ReadSeq
[ivy:retrieve] 	confs: [default]
[ivy:retrieve] 	0 artifacts copied, 3 already retrieved (0kB/2ms)

-pre-init:

-init-private:

-init-user:

-init-project:

-init-macrodef-property:

-do-init:

-post-init:

-init-check:

-init-ap-cmdline-properties:

-init-macrodef-javac-with-processors:

-init-macrodef-javac-without-processors:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/3:javac

-init-macrodef-javac:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/3:depend

-init-macrodef-test-impl:

-init-macrodef-junit-init:

-init-macrodef-junit-single:

-init-test-properties:

-init-macrodef-junit-batch:

-init-macrodef-junit:

-init-macrodef-junit-impl:

-init-macrodef-testng:

-init-macrodef-testng-impl:

-init-macrodef-test:

-init-macrodef-junit-debug:

-init-macrodef-junit-debug-batch:

-init-macrodef-junit-debug-impl:

-init-macrodef-test-debug-junit:

-init-macrodef-testng-debug:

-init-macrodef-testng-debug-impl:

-init-macrodef-test-debug-testng:

-init-macrodef-test-debug:

-init-debug-args:

-init-macrodef-nbjpda:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/1:nbjpdastart

-init-macrodef-debug:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/3:debug

-init-macrodef-java:
Trying to override old definition of task http://www.netbeans.org/ns/j2se-project/1:java

-init-presetdef-jar:

-init-ap-cmdline-supported:

-init-ap-cmdline:

init:

-deps-jar-init:

deps-jar:

-warn-already-built-jar:
[propertyfile] Updating property file: /RDPTools/Clustering/build/built-jar.properties

-check-automatic-build:

-clean-after-automatic-build:

-verify-automatic-build:

-pre-pre-compile:

-pre-compile:

-copy-persistence-xml:

-compile-depend:

-do-compile:
    [javac] Compiling 73 source files to /RDPTools/ReadSeq/build/classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 5
    [javac] error: Source option 5 is no longer supported. Use 6 or later.
    [javac] error: Target option 1.5 is no longer supported. Use 1.6 or later.

BUILD FAILED
/RDPTools/Clustering/nbproject/build-impl.xml:896: The following error occurred while executing this line:
/RDPTools/Clustering/nbproject/build-impl.xml:1470: The following error occurred while executing this line:
/RDPTools/AlignmentTools/nbproject/build-impl.xml:896: The following error occurred while executing this line:
/RDPTools/AlignmentTools/nbproject/build-impl.xml:1414: The following error occurred while executing this line:
/RDPTools/ReadSeq/nbproject/build-impl.xml:920: The following error occurred while executing this line:
/RDPTools/ReadSeq/nbproject/build-impl.xml:300: Compile failed; see the compiler error output for details.

Total time: 1 second
Makefile:15: recipe for target 'Clustering/dist/Clustering.jar' failed
make: *** [Clustering/dist/Clustering.jar] Error 1

**Here is additional relevant version information:**

(Java)
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)

(ant)
Apache Ant(TM) version 1.10.5 compiled on March 28 2019

Thank you!

**Comment by gunturus** [comment]
You need Ant 1.9. that should fix the problem

**Comment by RachelDanie** [comment]
Thanks Santosh! I was just a little confused about whether the ant version
should matter after reading this stackoverflow post that seemed to indicate
the java version was more important. Curious if you had thoughts on this
before i try to change ant versions.
Thanks!

**Comment by RachelDanie** [comment]
Sorry link here:
https://stackoverflow.com/questions/43354118/installing-multiple-versions-of-ant-on-same-machine
