### ISSUE TITLE
which version?

### ISSUE THREAD

**Issue by sariya** [rdpstaff/RDPTools#4]
Hello Team,

Thanks for maintaining this tool, and repository.
I downloaded the directory, followed instructions as on readme and install, typed "make", which resulted in successful build. I get couple of .jar files, including with the classifier jar.
My query:
Which version of RDP is it?
java -Xmx1g -jar classifier.jar -v 
or running without any flag doesn't spit version of classifier present.

Kindly help.

**Comment by rdpstaffmsu** [comment]
Hi, Sanjeev,

The version of RDP Classifier is current, i.e. 2.10.2 (
http://sourceforge.net/projects/rdp-classifier/files/rdp-classifier/).
Sorry we did not include this info in the command-line output.

Benli Chai

On Tue, Aug 4, 2015 at 9:01 AM, Sanjeev <notifications@github.com> wrote:

> Hello Team,
>
> Thanks for maintaining this tool, and repository.
> I downloaded the directory, followed instructions as on readme and
> install, typed "make", which resulted in successful build. I get couple of
> .jar files, including with the classifier jar.
> My query:
> Which version of RDP is it?
> java -Xmx1g -jar classifier.jar -v
> or running without any flag doesn't spit version of classifier present.
>
> Kindly help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rdpstaff/RDPTools/issues/4>.
>



-- 
RDP Staff
Ribosomal Database Project
Center for Microbial Ecology
Michigan State University
567 Wilson Rd. Room 2225 A
East Lansing, MI 48824
(517) 353-3842

**Comment by sariya** [comment]
Hi Benli,
Thanks for your response.

**Comment by kim-fehl** [comment]
Dear developers, don't you want to include this info into some '--version' option output. I use such commands to automatically log out versions of the software used in my pipelines, and most of it has such options...

> Sorry we did not include this info in the command-line output.
