### ISSUE TITLE
rdpclassifiertraindata/data.tgz Missing. Build fail

### ISSUE THREAD

**Issue by Nahush90** [rdpstaff/RDPTools#6]
Running make.. works till the mentioned file is tried to download. 
jar:
     [echo] To run this application from the command line without Ant, try:
     [echo] java -jar "/home/clevergene/swdump/RDPTools/TaxonomyTree/dist/TaxonomyTree.jar"

-check-automatic-build:

-clean-after-automatic-build:

-verify-automatic-build:

-pre-pre-compile:

-pre-compile:

-copy-persistence-xml:

-compile-depend:

-do-compile:

-post-compile:

compile:

-pre-jar:

-post-jar:

download-traindata:
      [get] Getting: http://rdp.cme.msu.edu/download/rdpclassifiertraindata/data.tgz
      [get] To: /home/clevergene/swdump/RDPTools/classifier/build/classes/data.tgz
      [get] Error opening connection java.io.IOException: Server returned HTTP response code: 502 for URL: http://rdp.cme.msu.edu/download/rdpclassifiertraindata/data.tgz
      [get] Error opening connection java.io.IOException: Server returned HTTP response code: 502 for URL: http://rdp.cme.msu.edu/download/rdpclassifiertraindata/data.tgz
      [get] Error opening connection java.io.IOException: Server returned HTTP response code: 502 for URL: http://rdp.cme.msu.edu/download/rdpclassifiertraindata/data.tgz
      [get] Can't get http://rdp.cme.msu.edu/download/rdpclassifiertraindata/data.tgz to /home/clevergene/swdump/RDPTools/classifier/build/classes/data.tgz

BUILD FAILED
/home/clevergene/swdump/RDPTools/classifier/build.xml:50: Can't get http://rdp.cme.msu.edu/download/rdpclassifiertraindata/data.tgz to /home/clevergene/swdump/RDPTools/classifier/build/classes/data.tgz

Total time: 14 seconds
make: *** [classifier/dist/classifier.jar] Error 1

**Comment by rdpstaffmsu** [comment]
Dear user,

Our DNS server had been down for a short while. That must contribute to the
problem. Do you want to try again and let me know how it goes? Thank you.

Sincerely,

Benli Chai
RDP Staff

On Fri, Sep 18, 2015 at 7:52 AM, Nahush90 <notifications@github.com> wrote:

> Running make.. works till the mentioned file is tried to download.
> jar:
> [echo] To run this application from the command line without Ant, try:
> [echo] java -jar
> "/home/clevergene/swdump/RDPTools/TaxonomyTree/dist/TaxonomyTree.jar"
>
> -check-automatic-build:
>
> -clean-after-automatic-build:
>
> -verify-automatic-build:
>
> -pre-pre-compile:
>
> -pre-compile:
>
> -copy-persistence-xml:
>
> -compile-depend:
>
> -do-compile:
>
> -post-compile:
>
> compile:
>
> -pre-jar:
>
> -post-jar:
>
> download-traindata:
> [get] Getting:
> http://rdp.cme.msu.edu/download/rdpclassifiertraindata/data.tgz
> [get] To:
> /home/clevergene/swdump/RDPTools/classifier/build/classes/data.tgz
> [get] Error opening connection java.io.IOException: Server returned HTTP
> response code: 502 for URL:
> http://rdp.cme.msu.edu/download/rdpclassifiertraindata/data.tgz
> [get] Error opening connection java.io.IOException: Server returned HTTP
> response code: 502 for URL:
> http://rdp.cme.msu.edu/download/rdpclassifiertraindata/data.tgz
> [get] Error opening connection java.io.IOException: Server returned HTTP
> response code: 502 for URL:
> http://rdp.cme.msu.edu/download/rdpclassifiertraindata/data.tgz
> [get] Can't get
> http://rdp.cme.msu.edu/download/rdpclassifiertraindata/data.tgz to
> /home/clevergene/swdump/RDPTools/classifier/build/classes/data.tgz
>
> BUILD FAILED
> /home/clevergene/swdump/RDPTools/classifier/build.xml:50: Can't get
> http://rdp.cme.msu.edu/download/rdpclassifiertraindata/data.tgz to
> /home/clevergene/swdump/RDPTools/classifier/build/classes/data.tgz
>
> Total time: 14 seconds
> make: *** [classifier/dist/classifier.jar] Error 1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rdpstaff/RDPTools/issues/6>.
>



-- 
RDP Staff
Ribosomal Database Project
Center for Microbial Ecology
Michigan State University
567 Wilson Rd. Room 2225 A
East Lansing, MI 48824
(517) 353-3842

**Comment by Nahush90** [comment]
Hi Benil,

Thanks for the update, I just tried now. Its working fine.

Thanks for your response.
